//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace speedyRecruitApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int Ref_Id { get; set; }
        public string Ref_Name { get; set; }
        public string Ref_Contact_No { get; set; }
        public string Ref_Email { get; set; }
        public string Ref_Position { get; set; }
        public string Ref_Company_Name { get; set; }
        public int Candidate_Id { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
